### ISSUE TITLE
Linux installation

### ISSUE THREAD

**Issue by StefanUlbrich** [HBPNeurorobotics/BlenderRobotDesigner#16]
Installation script fails (at least on Ubuntu 17.04 with the shipped package). Packages cannot be installed as a user (i.e., the install script) as blender uses the system's Python3 installation.

Try to install to ~/.config/scripts/modules instead.

**Comment by benef23** [comment]
Python packages are now installed to ~/.config/scripts/modules and the installation script should now work with Ubuntu shipped Blender.
