### ISSUE TITLE
issue: z and y coordinates switch when placing 1st child segment

### ISSUE THREAD

**Issue by JWeinland** [HBPNeurorobotics/BlenderRobotDesigner#18]
hey,
there's an issue when placing the first child segment after creating the root segment. 
When entering the model name and root segment name and creating a child bone right after, the Euler Postitions of the child segment get mixed up (z = -y, y =z, x=x) however the positions snap in their right postition after moving the root segment.

Best regard

**Comment by benef23** [comment]
Hi JWeinland,
thanks for reporting this issue. It should be fixed with the latest update.
Best regards

**Comment by benef23** [comment]
Hi JWeinland,
thanks for reporting this issue. It should be fixed with the latest update.
Best regards
