### ISSUE TITLE
Scaling Robot

### ISSUE THREAD

**Issue by JWeinland** [HBPNeurorobotics/BlenderRobotDesigner#23]
Hi,
I am trying to adjust the size of a robot head in BlenderRobotDesigner to match the size of a already existing robot. However even though the head looks fine in BRD, at a certain threshold the head "explodes" in Gazebo.
 "Autodesk Inventor" was used to create the .stl files. When importing those files in Blender they get scaled up several orders of magnitude , changing units in BRD or re scaling in CAD does not help.
I am not sure if re scaling is a feature provided in BRD but it would most definitely be helpful.
Best regards

![screenshot from 2017-05-10 20-54-58](https://user-images.githubusercontent.com/25507882/27818876-05925c7a-6098-11e7-822e-3357b64cf7b4.png)

**Comment by benef23** [comment]
Dear JWeinland,
Scaling is definitely an important aspect for the Robots in Gazebo. Therefore, we now support basic scaling for meshes within the Robot Designer, and consider scaling on import as well as export. Please find the related parameters in the Geometrie Properties section.
Best Regards
