### ISSUE TITLE
Load stuck on Import URDF - ROS package

### ISSUE THREAD

**Issue by t-schnell** [HBPNeurorobotics/BlenderRobotDesigner#24]
When trying to import from a urdf in a package with a missing package.xml file, RobotDesigner gets stuck without any kind of error message.

To reproduce the problem, I created a folder in my catkin workspace containing nothing but a urdf folder with an empty "test.urdf" file and tried to import this via the "Import URDF - ROS package" function. The result was the previosly described infinite load. Once I added an empty "package.xml" in the main folder, I get a correct "SAXParseException" instead.

**Comment by benef23** [comment]
The main supported model format of the Neurorobotics Platform is SDF (www.sdformat.org) and so the focus of the Robot Designer is currently on the SDF format. We disabled URDF support temporarily, and will work on full URDF support on user request with a revised import/export implementation.
