### ISSUE TITLE
Trouble with installation

### ISSUE THREAD

**Issue by Kobra299** [HBPNeurorobotics/BlenderRobotDesigner#46]
I have tried to install the add-on but it does not work with blender 2.79 on Windows 7 so any help in solving this is most welcome

the issue's seem to be with the script for it in the install.blend file

**Comment by benef23** [comment]
Please open a terminal as administrator, start blender and run the script. This may solve a potential permission error for installing python dependencies or gives further hints that lead to this error

**Comment by Kobra299** [comment]
how would I do that on a Windows system

**Comment by benef23** [comment]
As a first step you could search for blender in the Windows Start Menu, then right click and "Run as administrator" and try reinstalling the plugin. 
If this does not work:
Open your Windows start menu and search for "Command Prompt", right click and "Run as administrator". With "cd" + the folder you can navigate to your Blender installation. Then you can run it with "blender.exe". Install the plugin, and post a screenshot of the terminal output here.

**Comment by Kobra299** [comment]
I managed to get it to install just troublesome as some of the python blender info is old

**Comment by benef23** [comment]
can you just indicate what helped you to improve the installation process?

**Comment by Kobra299** [comment]
basically the part about running in admin you may have to check the security settings for the folder by going into the blender folder and right clicking it
