### ISSUE TITLE
Unable to see the add-on on Ubuntu 16.04

### ISSUE THREAD

**Issue by ShravanTata** [HBPNeurorobotics/BlenderRobotDesigner#53]
Hello,

I have currently installed blender v2.79 as apt package.
I then followed the instructions to install the add-on.
I managed to get the RD installation complete message.
Unfortunately I still do not see the add-on, I also tried and I see that the add-on is enabled in the user preferences settings!
Thanks in advance,

**Comment by EloyRC** [comment]
Hi, I have the same issue:
blender v2.79 (ubuntu 18.04) + I can't see the tab after installing

**Comment by ShravanTata** [comment]
Hey EloyRC,

I was able to successfully install the package and the tabbar is now visible for me. 
Are you sure you have all the necessary packages installed?
I did manual install and found that several packages weren't installed and this fixed the issue. 
To do so you need to use the python from blender package and not the default system python. 
Let me know if you need help with this. 

Regards,
Shravan

**Comment by EloyRC** [comment]
Hey ShravanTata,

I was going to try the installation again and when I opened blender the tab was there... I quite don't understand why since I had already reset blender a couple of times before without effect... Anyways, thanks for your help.
