### ISSUE TITLE
HBP panel not show for macOS Sierra 10.12.6 and Blender 2.79b

### ISSUE THREAD

**Issue by zengtaiping** [HBPNeurorobotics/BlenderRobotDesigner#57]
Hi! 
It's a great work that has been done.
I followed the [installation tutorials](http://hbpneurorobotics.github.io/BlenderRobotDesigner/user_manual/installation.html).
After the last step, **the “HBP” tab** corresponding to the Robot Designer does **not show up** in Blender. And I also changed the access permission for the file.
The log file shows:
```
[ERROR|      Core| __init__.py:081|<module>()] Could not import submodules:
	Exception:	ImportError
	Messages:
		No module named 'pyxb'
        Nesting Level 0:
```
However,`pip3 list` shows that I have already installed 'PyXB            1.2.6'.

I tried reinstalling BlenderRobotDesigner after removing robot_designer_plugin, but it did not work.

- Python version: 3.7.4
- macOS Sierra 10.12.6
- Blender 2.79b

Thanks in advance!

**Comment by benef23** [comment]
Dear zengtaiping,
Blender comes with its own python3, so even though you may find pyxb in your system python it might not be available in Blenders python. You should find the blender python package in some location like blender>\2.xx\python\bin, make sure to install pyxb with this python package.
Best
BF

**Comment by zengtaiping** [comment]
Thanks for your reply. @benef23 
I found the pyxb 1.2.5 is needed in version 2.79.
I fixed this by the following steps:
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
./python3.5m get-pip.py
./python3.5m -m pip install pyxb==1.2.5
```
I share it and hopefully help others with same troubles.
